name: Mobile App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: qualcli
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Create required directories
      run: |
        mkdir -p logs
        mkdir -p builds

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .  # Install package in development mode
        npm install

    - name: Start backend services
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        # Initialize database
        python scripts/init_db.py
        
        # Start FastAPI server
        uvicorn backend.main:app --host 0.0.0.0 --port 8002 &
        sleep 5  # Wait for server to start
        
        # Start Celery worker
        celery -A backend.queue.celery_app worker -l info &
        sleep 5  # Wait for worker to start

    - name: Run tests
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        # Submit test job through CLI
        python -m cli.main submit \
          --org-id "browserstack-demo" \
          --app-version-id "wikipedia-v1.0" \
          --target browserstack \
          --priority 5 \
          --test tests/appwright1.spec.js 